In [ ]:
''' 
作業一

      array1 = np.array([[10, 8], [3, 5]])

運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
運用上列array計算特徵值、特徵向量?
運用上列array計算SVD?
'''

In [1]:
import numpy as np 
import numpy.linalg as LA

In [4]:
#array1 = np.array([[10, 8], [3, 5]])
#運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
A =  np.array([[10, 8], [3, 5]])
A

array([[10,  8],
       [ 3,  5]])

In [6]:
Ainv= LA.inv(A)
Ainv

array([[ 0.19230769, -0.30769231],
       [-0.11538462,  0.38461538]])

In [9]:
#運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
#Ans: 是
IA=np.dot(A,Ainv)
IA

array([[1., 0.],
       [0., 1.]])

In [13]:
#運用上列array計算特徵值、特徵向量?
w, v = LA.eig(A)
#特徵值
w


array([13.,  2.])

In [14]:
#特徵向量
v

array([[ 0.93632918, -0.70710678],
       [ 0.35112344,  0.70710678]])

In [15]:
#運用上列array計算SVD?
u, s, vh = np.linalg.svd(A)
u

array([[-0.91663818, -0.39971796],
       [-0.39971796,  0.91663818]])

In [16]:
s

array([13.94721714,  1.86417116])

In [17]:
vh

array([[-0.74319741, -0.6690722 ],
       [-0.6690722 ,  0.74319741]])

In [2]:
''' 作業二

請比較對一個 100 x 100 * 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。
如何從一個陣列中，找出出現頻率最高的數值與位置？
如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。
'''

' 作業二\n\n請比較對一個 100 x 100 * 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。\n如何從一個陣列中，找出出現頻率最高的數值與位置？\n如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。\n'

In [22]:
#請比較對一個 100 x 100 * 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。
a = np.random.randint(0, 100, 1000000).reshape(100, 100, 100)
 

(100, 100, 100)

In [30]:
%timeit  a=2
for i in a.flat:
    i = i+1


10.3 ns ± 0.0533 ns per loop (mean ± std. dev. of 7 runs, 100000000 loops each)


In [11]:
#2. 如何從一個陣列中，找出出現頻率最高的數值與位置？
A = np.random.randint(0,5,20)
A

array([2, 0, 2, 4, 2, 4, 3, 4, 1, 2, 1, 0, 1, 0, 0, 1, 4, 4, 2, 3])

In [12]:
np.bincount(A)

array([4, 4, 5, 2, 5], dtype=int64)

In [13]:
#數字
rint = np.bincount(A).argmax()
rint

2

In [14]:
#位置
np.where(A == rint)[0]

array([ 0,  2,  4,  9, 18], dtype=int64)

In [15]:
#如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。
a = np.random.randint(10, size=6) 
print(a.tolist())
print(list(a))


[5, 3, 8, 3, 0, 1]
[5, 3, 8, 3, 0, 1]


In [19]:
c=a.tolist()
print(type(c))
d=list(a)
print(type(d))

<class 'list'>
<class 'list'>
