In [1]:
import numpy as np

In [2]:
np .__version__

'1.18.1'

In [28]:
#生成一個等差數列，首數為 0，尾數為 20，公差為 1 的數列
a= np.arange(0,21,1)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [32]:
#將數列取出偶數
a[2::2]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [31]:
#將數列取出3的倍數
a[3::3]

array([ 3,  6,  9, 12, 15, 18])