In [17]:
import numpy as np

#將下兩列 array 存成 npz 檔 array1 = np.array(range(30)) array2 = np.array([2,3,5])
array1 = np.array(range(30))
array2 = np.array([2,3,5])
np.savez('multi_array.npz', array1, array2) 

In [18]:
#讀取剛剛的npz檔，加入下列array一起存成新的npz檔array3 = np.array([[4,5,6],[1,2,3]])
array3 = np.array([[4,5,6],[1,2,3]])
npzfile = np.load('multi_array.npz')
keys=npzfile.files
print(keys)
array1 = npzfile['arr_0']
array2 = npzfile['arr_1']
np.savez('new_multi_array.npz', array1, array2,array3) 

['arr_0', 'arr_1']


In [19]:
#驗證
npzfile = np.load('new_multi_array.npz')
keys=npzfile.files
print(keys)

['arr_0', 'arr_1', 'arr_2']


In [20]:
#1. [簡答題] 請問下列這三種方法有什麼不同？

'''
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
Ans:
sum() 是 python 內建的函式。np.sum(a) 跟 a.sum() 是陣列專有的函式。
'''


'\nprint(a.sum()) \nprint(np.sum(a))\nprint(sum(a)) \nAns:\nsum() 是 python 內建的函式。np.sum(a) 跟 a.sum() 是陣列專有的函式。\n'

In [21]:
#2. 請對一個 5x5 的隨機矩陣作正規化的操作。
A = np.random.random((5, 5))
A

array([[0.40669034, 0.47993756, 0.59127882, 0.02769239, 0.39582233],
       [0.3247855 , 0.93087137, 0.65711123, 0.87450958, 0.16401251],
       [0.41448454, 0.47693372, 0.71719315, 0.11442596, 0.62502118],
       [0.08355177, 0.09030815, 0.8527183 , 0.89985165, 0.97774436],
       [0.41924478, 0.93675635, 0.0120962 , 0.72295629, 0.18659372]])

In [22]:
A = (A - A.min()) / (A.max() - A.min())
A

array([[0.40863138, 0.48448428, 0.59978638, 0.01615101, 0.39737676],
       [0.32381287, 0.95145956, 0.66796071, 0.89309275, 0.15732056],
       [0.41670285, 0.48137359, 0.73017998, 0.10597002, 0.63472909],
       [0.07399752, 0.08099425, 0.87052628, 0.91933635, 1.        ],
       [0.42163243, 0.95755389, 0.        , 0.73614813, 0.18070507]])

In [23]:
#3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1
B = np.random.random(12)
B[B.argmax()] = -1
print (B)

[ 0.84995819 -1.          0.68975971  0.0618447   0.62153593  0.14332803
  0.46945036  0.5888606   0.63119403  0.06666941  0.54864732  0.55011526]


In [24]:
B

array([ 0.84995819, -1.        ,  0.68975971,  0.0618447 ,  0.62153593,
        0.14332803,  0.46945036,  0.5888606 ,  0.63119403,  0.06666941,
        0.54864732,  0.55011526])