In [3]:
import numpy as np 
import numpy.linalg as LA

In [4]:
#array1 = np.array([[10, 8], [3, 5]])
#運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
A =  np.array([[10, 8], [3, 5]])
A

array([[10,  8],
       [ 3,  5]])

In [6]:
Ainv= LA.inv(A)
Ainv

array([[ 0.19230769, -0.30769231],
       [-0.11538462,  0.38461538]])

In [9]:
#運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
IA=np.dot(A,Ainv)
IA

array([[1., 0.],
       [0., 1.]])

In [13]:
#運用上列array計算特徵值、特徵向量?
w, v = LA.eig(A)
#特徵值
w


array([13.,  2.])

In [14]:
#特徵向量
v

array([[ 0.93632918, -0.70710678],
       [ 0.35112344,  0.70710678]])

In [15]:
#運用上列array計算SVD?
u, s, vh = np.linalg.svd(A)
u

array([[-0.91663818, -0.39971796],
       [-0.39971796,  0.91663818]])

In [16]:
s

array([13.94721714,  1.86417116])

In [17]:
vh

array([[-0.74319741, -0.6690722 ],
       [-0.6690722 ,  0.74319741]])