In [2]:
import numpy as np

In [21]:
#正常的談話的聲壓為 20000 微巴斯卡，請問多少分貝?
Gdb = 20 * np.log10(20000/20)
print('聲壓為 20000 upa是 : {} 分貝'.format(Gdb))

聲壓為 20000 upa是 : 60.0 分貝


In [3]:
#30 分貝的聲壓會是 50 分貝的幾倍?
#---30分貝的聲壓 30 = 20log10(v30/20)=> 1.5 = log10(v30/20)
v30 = np.power(10,1.5) * 20 
#---50分貝的聲壓 50 = 20log10(v50/20)=> 2.5 = log10(v50/20)
v50 = np.power(10,2.5) * 20
## 求倍數
ans = v30/v50
print('30 分貝的聲壓會是50分貝的聲壓的 : {} : 倍'.format(ans))

30 分貝的聲壓會是50分貝的聲壓的 : 0.09999999999999999 : 倍


In [4]:
#1. [簡答題] 請問下列程式碼，運算結果分別為何？
a = np.array( [20,30,40,50] )
b = np.array( [1,2,3,4] ) 
c = 1
d = np.array( [1] )
e = np.array( [1,2] ) 

In [6]:
#2. 如何在不用迴圈的情況下計算 (A+B)*(-A/2) ？那用迴圈怎麼做？
#不用廻圈
ans1=(a+b)*((a *-1)/2)
ans1

array([ -210.,  -480.,  -860., -1350.])

In [7]:
#3. 請問如何計算「1x6 的單位矩陣」和「6x1 的單位矩陣」的內積和外積？
A = np.ones((1,6))
B = np.ones((6,1))


In [8]:
A

array([[1., 1., 1., 1., 1., 1.]])

In [9]:
B

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [10]:
print(A * B)
print(A @ B)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[6.]]
